### ISSUE TITLE
"GithHub" typo on page 3 of the Writing Checklist

### ISSUE THREAD

**Issue by samm82** [smiths/capTemplate#3]
Page 3 of the Writing Checklist says "GithHub" instead of "GitHub"

https://github.com/smiths/capTemplate/blob/42b49e165dc3c98b50de28612c2254b4170fefc2/docs/Checklists/Writing-Checklist.tex#L122-L125

**Comment by smiths** [comment]
I misspelled closes in the commit (071eb23) message, so I'll close this manually.  :smile:
