### ISSUE TITLE
Typos in "source" bullet point of Problem Statement and Goals Checklist 

### ISSUE THREAD

**Issue by samm82** [smiths/capTemplate#4]
Based on the formatting of [Markdown](https://en.wikipedia.org/wiki/Markdown) and [Emacs Org Mode](https://en.wikipedia.org/wiki/Org-mode), this bullet point capitalizes/spells ("emaccs" vs. "Emacs") these tools incorrectly:

https://github.com/smiths/capTemplate/blob/42b49e165dc3c98b50de28612c2254b4170fefc2/docs/Checklists/ProbState-Checklist.tex#L35-L39

Also, since "etc." is used, there isn't a need to have the "or"s in this bullet point.

**Comment by smiths** [comment]
Thanks @samm82.  Nice to see that someone is actually using/reading one of my checklists.  Glad to have the critique.
