### ISSUE TITLE
SRS Abbreviations and Acronyms conflict: T vs TM

### ISSUE THREAD

**Issue by balacij** [smiths/capTemplate#5]
The last entry of the Table of Abbreviations and Acronyms defines an acronym, "T", for "Theoretical Model"s, but "T" is only used in the document (below), while the rest of the references to "Theoretical Models"/"Theory Models" use "TM". I think "TM" is what we should be using.

![image](https://user-images.githubusercontent.com/1627302/214685707-0d4c38b6-da58-4652-be0f-b3fc9579c374.png)

![image](https://user-images.githubusercontent.com/1627302/214686311-9d6fcb60-1f6c-4d62-8bce-c9a326c49260.png)

**Comment by smiths** [comment]
Yes, good point @balacij.  Thank you for pointing out the error.  All of the other major components have two-letter acronyms (DD, GD, IM), so the Theoretical Model really should be TM.

**Comment by samm82** [comment]
This abbreviation should be updated throughout the rest of the document:
https://github.com/smiths/capTemplate/blob/a558bc457dbc76e713362a1477c0b03ea0d27c45/docs/SRS/SRS.tex#L56-L58
https://github.com/smiths/capTemplate/blob/a558bc457dbc76e713362a1477c0b03ea0d27c45/docs/SRS/SRS.tex#L629-L633
https://github.com/smiths/capTemplate/blob/a558bc457dbc76e713362a1477c0b03ea0d27c45/docs/SRS/SRS.tex#L638-L642

And potentially here as well (although this could likely be automated by the template itself when generating a TM).
https://github.com/smiths/capTemplate/blob/a558bc457dbc76e713362a1477c0b03ea0d27c45/docs/SRS/SRS.tex#L661-L662

I think the first command for table number should be changed to "TB" to prevent an overlap and be consistent.
https://github.com/smiths/capTemplate/blob/a558bc457dbc76e713362a1477c0b03ea0d27c45/docs/SRS/SRS.tex#L59-L61

**Comment by smiths** [comment]
Thank you @samm82 (and @balacij).  I was sloppy in the template.  I found some other inconsistencies in the references and labels.  I fixed the above and the other things I found in 8ae7fd7.
